"""
Item list definitions for Albion Cost Calculator
Contains all item names and default tier/enchantment configurations
"""

# Default tiers to analyze
DEFAULT_TIERS = ["T5", "T6", "T7"]

# Default enchantment levels
DEFAULT_ENCHANTS = ["", "@1", "@2"]

# All available item names
# Uncomment items you want to include in the analysis
ALL_ITEM_NAMES = [
    "OFF_SHIELD",
    "OFF_BOOK",
    "OFF_TORCH",
    # "CAPE",
    # "BAG",
    # "HEAD_PLATE_SET1",
    # "HEAD_PLATE_SET2",
    # "HEAD_PLATE_SET3",
    # "ARMOR_PLATE_SET1",
    # "ARMOR_PLATE_SET2",
    # "ARMOR_PLATE_SET3",
    # "SHOES_PLATE_SET1",
    # "SHOES_PLATE_SET2",
    # "SHOES_PLATE_SET3",
    # "HEAD_LEATHER_SET1",
    # "HEAD_LEATHER_SET2",
    # "HEAD_LEATHER_SET3",
    # "ARMOR_LEATHER_SET1",
    # "ARMOR_LEATHER_SET2",
    # "ARMOR_LEATHER_SET3",
    # "SHOES_LEATHER_SET1",
    # "SHOES_LEATHER_SET2",
    # "SHOES_LEATHER_SET3",
    # "HEAD_CLOTH_SET1",
    # "HEAD_CLOTH_SET2",
    # "HEAD_CLOTH_SET3",
    # "ARMOR_CLOTH_SET1",
    # "ARMOR_CLOTH_SET2",
    # "ARMOR_CLOTH_SET3",
    # "SHOES_CLOTH_SET1",
    # "SHOES_CLOTH_SET2",
    # "SHOES_CLOTH_SET3",
    # "2H_BOW",
    # "2H_WARBOW",
    # "2H_LONGBOW",
    # "2H_CROSSBOW",
    # "2H_CROSSBOWLARGE",
    # "MAIN_1HCROSSBOW",
    # "MAIN_CURSEDSTAFF",
    # "2H_CURSEDSTAFF",
    # "2H_DEMONICSTAFF",
    # "MAIN_FIRESTAFF",
    # "2H_FIRESTAFF",
    # "2H_INFERNOSTAFF",
    # "MAIN_FROSTSTAFF",
    # "2H_FROSTSTAFF",
    # "2H_GLACIALSTAFF",
    # "MAIN_ARCANESTAFF",
    # "2H_ARCANESTAFF",
    # "2H_ENIGMATICSTAFF",
    # "MAIN_HOLYSTAFF",
    # "2H_HOLYSTAFF",
    # "2H_DIVINESTAFF",
    # "MAIN_NATURESTAFF",
    # "2H_NATURESTAFF",
    # "2H_WILDSTAFF",
    # "MAIN_DAGGER",
    # "2H_DAGGERPAIR",
    # "2H_CLAWPAIR",
    # "MAIN_SPEAR",
    # "2H_SPEAR",
    # "2H_GLAIVE",
    # "MAIN_AXE",
    # "2H_AXE",
    # "2H_HALBERD",
    # "MAIN_SWORD",
    # "2H_CLAYMORE",
    # "2H_DUALSWORD",
    # "2H_QUARTERSTAFF",
    # "2H_IRONCLADEDSTAFF",
    # "2H_DOUBLEBLADEDSTAFF",
    # "MAIN_HAMMER",
    # "2H_POLEHAMMER",
    # "2H_HAMMER",
    # "MAIN_MACE",
    # "2H_MACE",
    # "2H_FLAIL",
    # "2H_KNUCKLES_SET1",
    # "2H_KNUCKLES_SET2",
    # "2H_KNUCKLES_SET3",
]
